plugin: netbox.netbox.nb_inventory
api_endpoint: https://netboxhomologacao.etipi.pi.gov.br"
validate_certs: false
config_context: true
group_by:
  - device_roles
  - sites
  - is_virtual
device_query_filters:
  - has_primary_ip: 'true'
vm_query_filters:
  - has_primary_ip: 'true'
